### ISSUE TITLE
xqed szótár nem indul

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk2#25]
> attila@attila-pc:~$ xqed
Traceback (most recent call last):
  File "/usr/bin/xqed", line 21, in <module>
    import Xqed
  File "/usr/lib/python2.7/site-packages/Xqed.py", line 21, in <module>
    from Tkinter import *
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 39, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ImportError: No module named _tkinter
attila@attila-pc:~$

**Comment by rezso** [comment]
A kidobott python-tkinter kellene neki.

**Comment by attuska** [comment]
Vissza a python-tkinter, vag ez is kidobandó?

**Comment by rezso** [comment]
Szerintem kidobandó:
https://github.com/uhulinux/ub-ubk2/commit/86be0fba32a51edf6d035d49afa1e60f1148c946
