### ISSUE TITLE
virt-manager nem indul

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk2#38]
> attila@attila-pc:~$ virt-manager
Traceback (most recent call last):
  File "/usr/share/virt-manager/virt-manager", line 35, in <module>
    from virtinst import util as util
  File "/usr/share/virt-manager/virtinst/__init__.py", line 89, in <module>
    from virtinst.distroinstaller import DistroInstaller
  File "/usr/share/virt-manager/virtinst/distroinstaller.py", line 23, in <module>
    from . import urlfetcher
  File "/usr/share/virt-manager/virtinst/urlfetcher.py", line 34, in <module>
    import requests
ImportError: No module named requests
attila@attila-pc:~$

**Comment by rezso** [comment]
python-requests

**Comment by attuska** [comment]
Megoldja, csomagszinten bele kell drótozni.
