### ISSUE TITLE
wammu nem indul

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk2#39]
> attila@attila-pc:~$ wammu
Traceback (most recent call last):
  File "/usr/bin/wammu", line 47, in <module>
    import Wammu.Locales
  File "/usr/lib/python2.7/site-packages/Wammu/Locales.py", line 31, in <module>
    import six
ImportError: No module named six
attila@attila-pc:~$

**Comment by rezso** [comment]
python-six

**Comment by attuska** [comment]
Megoldja, csomagszintre kell emelni.
