### ISSUE TITLE
sweethome3d java error

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk2#64]
A noveau drájverrel csupán merevgörcsben végzi a mostani és a legújabb verzió is.
Bármelyik nvida hivatalos csomaggal, nvidia-340, nvidia-390, nvidia pedig kilép egy figyelmeztető ablak után. Ebben figyelmeztet, hogy túl régi az OpenGL megjelenítő rendszer, és frissítsem a megjelenítő kártya meghajtóját.
Terminálban ezt hagyja ekkor:
>attila@attila-pc:~$ sweethome3d
com.jogamp.opengl.GLException: J3D-Renderer-1: Error making temp context(1) current: display 0x7f8bd010a730, context 0x7f8bd0ac13a8, drawable X11OnscreenGLXDrawable[Realized true,
	Factory   jogamp.opengl.x11.glx.X11GLXDrawableFactory@8b0c4ed,
	Handle    0x1e0008e,
	Surface   JAWTWindow[0x29166f65][JVM version: 1.8.0_202 (1.8.0 update 202)
JAWT version: 0x10004, CA_LAYER: false, isLayeredSurface false, bounds [ 0 / 0  741 x 357 ], insets [ l 0, r 0 - t 0, b 0 - 0x0], pixelScale 1.0x1.0, shallUseOffscreenLayer false, isOffscreenLayerSurface false, attachedSurfaceLayer 0x0, windowHandle 0x1e0008e, surfaceHandle 0x1e0008e, bounds [ 0 / 0  741 x 357 ], insets [ l 0, r 0 - t 0, b 0 - 0x0], window [0/0 741x357], pixels[scale 1.0, 1.0 -> 741x357], visible true, lockedExt false,
	config AWTGraphicsConfiguration[AWTGraphicsScreen[AWTGraphicsDevice[type .awt, connection :0.0, unitID 0, awtDevice X11GraphicsDevice[screen=0], handle 0x0], idx 0],
	chosen    GLCaps[glx vid 0x28, fbc 0x10f: rgba 8/8/8/8, opaque, accum-rgba 16/16/16/16, dp/st/ms 24/0/0, dbl, mono  , hw, GLProfile[GL4bc/GL4bc.hw], on-scr[.]],
	requested GLCaps[rgba 5/5/5/1, opaque, accum-rgba 0/0/0/0, dp/st/ms 24/0/0, dbl, mono  , hw, GLProfile[GL4bc/GL4bc.hw], on-scr[.]],
	X11GraphicsConfig[dev=X11GraphicsDevice[screen=0],vis=0x28],
	encapsulated X11GLXGraphicsConfiguration[X11GraphicsScreen[X11GraphicsDevice[type .x11, connection :0, unitID 0, handle 0x7f8bd010a730, owner true, JAWTToolkitLock[obj 0x10fc7810, isOwner true, <1dc7262d, 135e0ed4>[count 1, qsz 0, owner <J3D-Renderer-1>]]], idx 0], visualID 0x28, fbConfigID 0x10f,
	requested GLCaps[rgba 5/5/5/1, opaque, accum-rgba 0/0/0/0, dp/st/ms 24/0/0, dbl, mono  , hw, GLProfile[GL4bc/GL4bc.hw], on-scr[.]],
	chosen    GLCaps[glx vid 0x28, fbc 0x10f: rgba 8/8/8/8, opaque, accum-rgba 16/16/16/16, dp/st/ms 24/0/0, dbl, mono  , hw, GLProfile[GL4bc/GL4bc.hw], on-scr[.]]]],
	awtComponent com.eteks.sweethome3d.j3d.Component3DManager$ObservedCanvas3D[canvas2,0,0,741x357],
	surfaceLock <f74595b, 1e105ced>[count 1, qsz 0, owner <J3D-Renderer-1>]]]
	at jogamp.opengl.x11.glx.X11GLXContext.createImpl(X11GLXContext.java:393)
	at jogamp.opengl.GLContextImpl.makeCurrentWithinLock(GLContextImpl.java:765)
	at jogamp.opengl.GLContextImpl.makeCurrent(GLContextImpl.java:648)
	at jogamp.opengl.GLContextImpl.makeCurrent(GLContextImpl.java:586)
	at javax.media.j3d.JoglPipeline.createNewContext(JoglPipeline.java:6411)
	at javax.media.j3d.Canvas3D.createNewContext(Canvas3D.java:4612)
	at javax.media.j3d.Canvas3D.createNewContext(Canvas3D.java:2386)
	at javax.media.j3d.Renderer.doWork(Renderer.java:881)
	at javax.media.j3d.J3dThread.run(J3dThread.java:271)
Error in Java 3D : 3 Renderer: Error creating Canvas3D graphics contextX11Util.Display: Shutdown (JVM shutdown: true, open (no close attempt): 2/2, reusable (open, marked uncloseable): 0, pending (open in creation order): 2)
X11Util: Open X11 Display Connections: 2
X11Util: Open[0]: NamedX11Display[:0, 0x7f8bd007d440, refCount 1, unCloseable false]
X11Util: Open[1]: NamedX11Display[:0, 0x7f8bd010a730, refCount 1, unCloseable false]
attila@attila-pc:~$

**Comment by attuska** [comment]
UBK1 és UBK3 esetén jó!

**Comment by attuska** [comment]
Nouveauval terminálban ezt hagyja az elején itt is:
>attila@attila-pc:~$ SWEETHOME3D_JAVA3D=1.5 sweethome3d
Exception in thread "main" java.lang.InternalError: XXX0 profile[1]: GL3bc -> profileImpl GL4bc !!! not mapped 

Rákeresve van is ilyen nyavalygás bőven, egy közülük: https://bugs.archlinux.org/task/58319

A java frissítés hatástalan. A sweethome3d frissítése is!
Még nem sikerült elindítani sehogyan sem, a splash képnél megáll.

**Comment by attuska** [comment]
Az indító szkript a hibás, kijavítva.
