### ISSUE TITLE
griffith nem indul

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk2#8]
> attila@attila-pc:~$ griffith
Traceback (most recent call last):
  File "/usr/bin/griffith", line 86, in <module>
    import add
  File "/usr/share/griffith/lib/add.py", line 31, in <module>
    import quick_filter
  File "/usr/share/griffith/lib/quick_filter.py", line 25, in <module>
    import db
  File "/usr/share/griffith/lib/db/__init__.py", line 30, in <module>
    from _objects import *
  File "/usr/share/griffith/lib/db/_objects.py", line 33, in <module>
    import validators
  File "/usr/share/griffith/lib/db/validators.py", line 26, in <module>
    from sqlalchemy.orm.interfaces import AttributeExtension, InstrumentationManager
ImportError: cannot import name InstrumentationManager
attila@attila-pc:~

**Comment by rezso** [comment]
https://bugs.launchpad.net/ubuntu/+source/griffith/+bug/1212397

**Comment by attuska** [comment]
Már rég megoldva.
https://github.com/uhulinux/ub-ubk2/commit/b09ba3be1d06e2c25523fff71f8eb4efde6ce938
