### ISSUE TITLE
gourmet nem indul

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk2#9]
Ez sem megy.

> attila@attila-pc:~$ gourmet
No gst player
No windows player
/usr/lib/python2.7/site-packages/gourmet/gtk_extras/mnemonic_manager.py:313: GtkWarning: Invalid input string
  widget.set_text_with_mnemonic(txt[0:index] + '_' + txt[index:])
/usr/lib/python2.7/site-packages/gourmet/GourmetRecipeManager.py:1003: GtkWarning: Invalid input string
  self.main.add(self.main_notebook)
IO Error [Errno 2] Nincs ilyen fájl vagy könyvtár: '/usr/share/doc/gourmet/LICENSE'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gourmet/GourmetRecipeManager.py", line 375, in show_about
    about.set_license(license_text)
UnboundLocalError: local variable 'license_text' referenced before assignment
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gourmet/GourmetRecipeManager.py", line 409, in show_help
    de.show_faq(os.path.join(doc_base,'FAQ'))
  File "/usr/lib/python2.7/site-packages/gourmet/gtk_extras/dialog_extras.py", line 1150, in show_faq
    d=SimpleFaqDialog(*args,**kwargs)
  File "/usr/lib/python2.7/site-packages/gourmet/gtk_extras/dialog_extras.py", line 622, in __init__
    self.parse_faq(faq_file)
  File "/usr/lib/python2.7/site-packages/gourmet/gtk_extras/dialog_extras.py", line 663, in parse_faq
    infile=open(infile)            
IOError: [Errno 2] Nincs ilyen fájl vagy könyvtár: '/usr/share/doc/gourmet/FAQ'
/usr/lib/python2.7/site-packages/gourmet/reccard.py:976: GtkWarning: UnitConverter: missing action UnitConverter
  main_vb.pack_start(self.ui_manager.get_widget('/RecipeEditorMenuBar'),expand=False,fill=False)
/usr/lib/python2.7/site-packages/gourmet/reccard.py:976: GtkWarning: Undo: missing action Undo
  main_vb.pack_start(self.ui_manager.get_widget('/RecipeEditorMenuBar'),expand=False,fill=False)
/usr/lib/python2.7/site-packages/gourmet/reccard.py:976: GtkWarning: Redo: missing action Redo
  main_vb.pack_start(self.ui_manager.get_widget('/RecipeEditorMenuBar'),expand=False,fill=False)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gourmet/gtk_extras/ratingWidget.py", line 242, in __init__
    self.image = StarImage(star_gen, value=start_value, upper=upper)
  File "/usr/lib/python2.7/site-packages/gourmet/gtk_extras/ratingWidget.py", line 172, in __init__
    self.set_value(value)
  File "/usr/lib/python2.7/site-packages/gourmet/gtk_extras/ratingWidget.py", line 181, in set_value
    self.stars.get_pixbuf(value,self.upper)
  File "/usr/lib/python2.7/site-packages/gourmet/gtk_extras/ratingWidget.py", line 80, in get_pixbuf
    pb=self.get_pixbuf_from_image(img)
  File "/usr/lib/python2.7/site-packages/gourmet/gtk_extras/ratingWidget.py", line 138, in get_pixbuf_from_image
    image.tostring(),
  File "/usr/lib/python2.7/site-packages/PIL/Image.py", line 740, in tostring
    raise NotImplementedError("tostring() has been removed. "
NotImplementedError: tostring() has been removed. Please call tobytes() instead.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gourmet/GourmetRecipeManager.py", line 1124, in show
    rc=reccard.RecCard(self)
  File "/usr/lib/python2.7/site-packages/gourmet/reccard.py", line 72, in __init__
    self.show()
  File "/usr/lib/python2.7/site-packages/gourmet/reccard.py", line 122, in show
    self.show_edit()
  File "/usr/lib/python2.7/site-packages/gourmet/reccard.py", line 104, in show_edit
    self.recipe_editor = RecEditor(self, self.rg,self.current_rec,new=self.new)
  File "/usr/lib/python2.7/site-packages/gourmet/reccard.py", line 848, in __init__
    self.setup_modules()
  File "/usr/lib/python2.7/site-packages/gourmet/reccard.py", line 911, in setup_modules
    instance = klass(self)
  File "/usr/lib/python2.7/site-packages/gourmet/reccard.py", line 1358, in __init__
    RecEditorModule.__init__(self, *args)
  File "/usr/lib/python2.7/site-packages/gourmet/plugin.py", line 429, in __init__
    self.setup_main_interface()
  File "/usr/lib/python2.7/site-packages/gourmet/reccard.py", line 1364, in setup_main_interface
    self.init_recipe_widgets()
  File "/usr/lib/python2.7/site-packages/gourmet/reccard.py", line 1407, in init_recipe_widgets
    self.update_from_database()
  File "/usr/lib/python2.7/site-packages/gourmet/reccard.py", line 1442, in update_from_database
    self.rw[e].set_value(int(getattr(self.current_rec,e) or 0))
  File "/usr/lib/python2.7/site-packages/gourmet/gtk_extras/ratingWidget.py", line 250, in set_value
    self.image.set_value(value)
AttributeError: 'StarButton' object has no attribute 'image'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gourmet/reccard.py", line 1082, in close_cb
    if self.new:
AttributeError: RecEditor instance has no attribute 'new'

**Comment by attuska** [comment]
Itt is megoldódott:
https://github.com/uhulinux/ub-ubk1/commit/ae991c7019863388417821123fe3fa11232a3451
